### PR TITLE
Integrate with file ID manager

### LINKED ISSUE #120: Integrate with File ID service

### PR DESCRIPTION
**Pull request by dlqqq**
Fixes #120.

- Input path is now tracked across file moves.
  - REST API remains identical. Accepts and returns `input_uri` attribute in payloads.
  - However, the DB record now stores `input_file_id` instead of `input_uri`. Scheduler methods invoke `file_id_manager.index()` upon create and invoke `file_id_manager.get_path()` upon describe.
- Adds new seed script in `dev/` directory, which now also accepts real template input files and generates real output files. The intended development flow is as follows:
```
cd dev/
python seed.py
jupyter lab
```

## Open questions

- Does updating the input URI need to be supported ATM? This is not implemented in the UI, so I don't see a pressing need to tackle this in this PR.

- Do we need to support file ID for the output prefix? @ellisonbg had raised this during our morning standup, but frankly I don't think it makes sense, as the output directory may not even exist at job creation. Look at the implementation for `Downloader#download()`:

```python
    def download(self):
        for output_format in self.output_formats:
            input_filepath = self.staging_paths[output_format]
            output_filename = os.path.basename(input_filepath)
            output_dir = resolve_path(self.output_prefix, self.root_dir)
            if not os.path.exists(output_dir):
                # vvvvvvvvvv
                os.makedirs(output_dir)
...
```

The download method creates the directories as needed upon download. Requiring a file ID for the output directory would mean we have to create the output directories on job creation rather than on download. I simply cannot envision a scenario in which a user would create a job, navigate to the newly created output directory, and then move that directory around and expect the files to still be populated there.

Aside from my concerns with the user experience, this also isn't possible with the current version of File ID, because the modified times of the directory will change upon creating new files out-of-band (like the Downloader is doing), which then assigns the output directory a new file ID, and the old file ID no longer can be resolved to a path.

## Notes

- [Without JS2, editing a file assigns it a new file ID and breaks the old one on Linux](https://github.com/jupyter-server/jupyter_server_fileid/issues/15). This means that editing an input file on Linux causes it to be effectively lost (e.g. won't show up in the list jobs table). To ensure this never happens for any user installing scheduler, we would either have to:
  - impose a hard dependency on JS2
  - add support for ext4 creation timestamps in file ID

### CODE REVIEW

**Comment by 3coins** [comment]
cc @bhadrip

**Comment by dlqqq** [comment]
@ellisonbg 

> If we defer creating the output directory until when the output files are downloaded, we risk creating the directory in the wrong place (relative to any changes the user may have made to their filesystem in the meantime).

I'm not sure I'm following your point. The absolute path of the output directory will only change if the user changes the server root after restarting the server. If we track them with file IDs such that the output directory is always at the same absolute path regardless of server root, then we have two issues:

1. File ID doesn't support `get_path()` outside the server root. So if we change the behavior of the extension such that output files always get downloaded to the same absolute path, then tracking that file ID is a complete no-go unless we are willing to fail downloads because their path is outside the server root.
2. Even if we drop file ID but maintain absolute output directories, then the user is unable to view the output files.

Furthermore, what happens if that output directory is deleted? Do we completely fail the job or do we just create a new directory over it anyways?

It's just not clear to me what usability gains justify the ambiguity of involved in both tracking output directories and making them absolute at job & job definition creation. We already have a staging area to address the concern of losing output files. IMO, downloading shouldn't mean "this is the one true copy for all servers", it just means "create a new copy relative to my server root". This is analogous to downloading files from the Internet -- downloading a file from Google Drive shouldn't fail because I already downloaded it in the past on a different computer.

> Another question is what we should pass to the backend. In your PR, you pass the file paths and ask the backend to translate to file ids. I was originally thinking we would never pass the file paths to the backend and only always pass them ids. I don't know what the right answer is, but we should discuss this point.

The client would have to make an extra round trip to call the File ID REST API first. What problem does this solve?

> Finally, we need to think about how search works. If a backend only tracks the ids, the search capability would need to translate any path queries to ids. The difficulty with that is the distance metrics on the space of file paths and file ids are completely different. This makes it essentially impossible to search for files with partial or fuzzy matching.

This is a great question. Let me think about this more deeply, as this is a cross-cutting concern for any extension that uses file ID, not just scheduler.

**Review by 3coins — COMMENTED** [review]
I am wondering if we can use a decorator to transition in and out of file_id/path. The decorator will change `input_uri` to use `file_id` while calling create and then back to using the paths in the return.

**Comment by ellisonbg** [comment]
Can we close this?

**Comment by dlqqq** [comment]
Upon further discussion with the team, we believe that the ideal behavior is to actually create a **snapshot** of the input file on job & job definition creation rather than attempting to track the state of the input file across its lifetime. Closing.

**Pull request closed without merging**
