### PR TITLE
Fix RTD and E2E CI workflows

### PR DESCRIPTION
**Pull request by andrii-i**
- Fixes ReadTheDocs build process (error example: https://readthedocs.org/projects/jupyter-scheduler/builds/22111095/) by adding readthedocs configuration file v2

### CODE REVIEW

**Comment by dlqqq** [comment]
I just rebased and squashed away the commit from the pre-commit bot. Will see if E2E tests pass after rerunning the pipeline.

**Comment by dlqqq** [comment]
Ah, this looks like an upstream change in Playwright that somehow slipped by, even when fixing `jupyterlab==4.0.3` in our tests. See here: https://github.com/jupyterlab/jupyterlab/issues/15116

**Comment by JasonWeill** [comment]
Not just our repo is affected; I had to upgrade readthedocs config in https://github.com/jupyter/jupyter/pull/698/ as well

**Comment by dlqqq** [comment]
Resolved this issue. Here was my thought process (this may be helpful to @andrii-i):
 
The PR that backports a fix for this issue to 4.0.x is https://github.com/jupyterlab/jupyterlab/pull/15118. Looking at the PR, we see it was merged in as commit `f73ea9acc67a5dd581e64b400018d3373d3676dc`. Then, I ran:

```
git tag --contains f73ea9acc67a5dd581e64b400018d3373d3676dc
```

to see that it was first included in the v4.0.6 release. This indicated to me that upgrading to v4.0.6 in our tests would be solve this CI failure. After making sure to also set this patch version for Galata and updating `ui-tests/yarn.lock`, I was able to get CI passing again.

**Review by dlqqq — APPROVED** [review]

**Comment by andrii-i** [comment]
Thank you @dlqqq

**Pull request merged**
