### PR TITLE
Changed column header to "Input file" in Notebook Job Definitions

### LINKED ISSUE #492: Inconsistent "Input file" column naming in the jobs table
## Description

It's "Input file" in Notebook Jobs table vs "Input filename" in Job Definitions table

Screenshot 2024-02-22 at 1 55 31 PM
Screenshot 2024-02-22 at 1 55 35 PM

## Expected behavior

"Input file" in both tables

### PR DESCRIPTION
**Pull request by srdas**
The Notebook Job Descriptions table now shows "Input file" in the column header instead of "Input filename". 
This makes the column header consistent across the *Notebook Jobs* tab and the  *Notebook Job Descriptions* tab.

Fixes #492

### CODE REVIEW

**Review by andrii-i — CHANGES_REQUESTED** [review]
Thank you @srdas. Change looks good to me. 

Couple of small comments:
- It’s a good practice to link the PR to the issue that it solves. It allows anyone looking at the PR to understand the context of the PR better (why it was created, what problem it solves) and is also helpful for tracking purposes (issue would show that there is a PR that might solve it, you can filter for issues with / without open PRs, issue with a linked PR is automatically closed on the PR merge). To do it, you can just type “fixes #ISSUENUMBER” is the PR description body or use github UI via Development dropdown on the right handside of the PR page (screen below). Here are the docs for the feature: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue. Could you please do that?
- When UI is affected, it's a good idea to post before / after screenshots (or at least "after"; or even GIFs for more complex cases) in the PR. This helps reviewers understand the change better, shows how code change affects the UI. Last but not least, helps yourself or someone else looking at your PR sometime later to quickly understand the impact of the PR. Could you please do it as well? With macos, it takes just a couple of clicks: cmd + shift + 4 -> click on the screen preview in the bottom right corner -> cmd + c -> cmd + v in the PR description https://support.apple.com/en-us/102646

**Comment by srdas** [comment]
Issue #492 

Before image:
image

After the change:
image

This makes both panels "Notebook Jobs" and "Notebook Job Definitions" consistent). See the panel for Notebook Jobs as well: 
image

**Comment by srdas** [comment]
Issue #492

I have updated the the column headers now to show "Input filename" in both tables. The new build is tested and shows the correct headers. We chose “filename” over “file” is because we don’t show the absolute or relative path, just the name of the file in any directory. Both tables are shown below:

Notebook Jobs

Notebook Jobs Definition

The code change was made in `list-jobs.tsx`

source change

**Review by andrii-i — APPROVED** [review]
Looks good. Thank you @srdas.

**Pull request merged**
